version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"

  database:
    image: mariadb:11.1.3-jammy
    ports: 
      - "8081:80"
    environment:
      PMA_HOST: tarea
      MYSQL_ROOTPASSWORD: 1q2w3e4r
      MYSQL_USER: root
      MYSQL_PASSWORD: 1q2w3e4r

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports: 
      - "8081:80"
    environment:
      PMA_HOST: tarea
      MYSQL_ROOTPASSWORD: 1q2w3e4r
      MYSQL_USER: root
      MYSQL_PASSWORD: 1q2w3e4r